/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const InterviewSession = IDL.Record({
  'overallScore' : IDL.Nat,
  'jobRole' : IDL.Text,
  'feedback' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'timestamp' : Time,
  'technicalScore' : IDL.Nat,
  'communicationScore' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'improvementRate' : IDL.Int,
  'averageConfidence' : IDL.Nat,
  'totalInterviews' : IDL.Nat,
  'averageScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInterviewSession' : IDL.Func([InterviewSession], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getInterviewSessions' : IDL.Func([], [IDL.Vec(InterviewSession)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedInterviewSessions' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const InterviewSession = IDL.Record({
    'overallScore' : IDL.Nat,
    'jobRole' : IDL.Text,
    'feedback' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'timestamp' : Time,
    'technicalScore' : IDL.Nat,
    'communicationScore' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'improvementRate' : IDL.Int,
    'averageConfidence' : IDL.Nat,
    'totalInterviews' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInterviewSession' : IDL.Func([InterviewSession], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getInterviewSessions' : IDL.Func(
        [],
        [IDL.Vec(InterviewSession)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedInterviewSessions' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };